
[colors.bright]
black = "#4b565c"
blue = "#7fbbb3"
cyan = "#83c092"
green = "#a7c080"
magenta = "#d699b6"
red = "#e67e80"
white = "#d3c6aa"
yellow = "#dbbc7f"

[colors.normal]
black = "#4b565c"
blue = "#7fbbb3"
cyan = "#83c092"
green = "#a7c080"
magenta = "#d699b6"
red = "#e67e80"
white = "#d3c6aa"
yellow = "#dbbc7f"

[colors.primary]
background = "#2b3339"
foreground = "#d3c6aa"

[font]
size = 13.0

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.bold_italic]
family = "MesloLGS NF"
style = "Italic"

[font.italic]
family = "MesloLGS NF"
style = "Italic"

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[selection]
save_to_clipboard = true
semantic_escape_chars = ''',â”‚`|:"' ()[]{}<>	'''

[window]
decorations = "Full"
opacity = 1.0

[general]
live_config_reload = true

